5/5 20:42:10 [8194] - [32minfo[39m:     .                              .o8                     oooo
5/5 20:42:10 [8194] - [32minfo[39m:   .o8                             "888                     `888
5/5 20:42:10 [8194] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 20:42:10 [8194] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 20:42:10 [8194] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 20:42:10 [8194] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 20:42:10 [8194] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 20:42:10 [8194] - [32minfo[39m: ==========================================================================
5/5 20:42:10 [8194] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 20:42:10 [8194] - [32minfo[39m:  
5/5 20:42:10 [8194] - [32minfo[39m: Running in: development
5/5 20:42:10 [8194] - [32minfo[39m: Time: Sat May 05 2018 20:42:10 GMT+0800 (CST)
5/5 20:42:10 [8194] - [32minfo[39m: Connected to MongoDB
5/5 20:42:10 [8194] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 20:42:10 [8194] - [32minfo[39m: SocketServer Running
5/5 20:42:10 [8194] - [34mdebug[39m: Checking Default Settings...
5/5 20:42:10 [8194] - [34mdebug[39m: Starting Runners...
5/5 20:42:10 [8194] - [32minfo[39m: TruDesk Ready
5/5 20:42:10 [8194] - [34mdebug[39m: Number of Tasks: 0
5/5 20:42:11 [Child:Cache:8196] - [34mdebug[39m: Pulled 0
5/5 20:42:11 [Child:Cache:8196] - [34mdebug[39m: Cache Loaded
5/5 20:42:14 [8194] - [34mdebug[39m: User successfully connected: hanjie
Error: [groups.hbs] Parse error on line 41:
...roup($event)">{{edit}</a></li>         
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'INVALID'
    at Parser.parseError (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:268:19)
    at Parser.parse (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:337:30)
    at HandlebarsEnvironment.parse (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at compileInput (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:515:19)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:524:18)
    at renderTemplate (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:483:13)
    at render (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:531:5)
    at renderIt (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:593:18)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:613:11
    at parseLayout (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:467:7)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:582:7
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:570:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
Error: [groups.hbs] Parse error on line 41:
...roup($event)">{{edit}</a></li>         
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'INVALID'
    at Parser.parseError (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:268:19)
    at Parser.parse (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:337:30)
    at HandlebarsEnvironment.parse (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at compileInput (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:515:19)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:524:18)
    at renderTemplate (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:483:13)
    at render (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:531:5)
    at renderIt (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:593:18)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:613:11
    at parseLayout (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:467:7)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:582:7
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:570:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5/5 20:45:59 [8194] - [34mdebug[39m: User disconnected: hanjie - 35ACxN2x8qgOGNiBAAAA
5/5 20:46:12 [8194] - [34mdebug[39m: User successfully connected: hanjie
5/5 20:49:41 [8194] - [34mdebug[39m: User disconnected: hanjie - s4XOAY1_CqSRsuoOAAAB
5/5 20:49:42 [8194] - [34mdebug[39m: User successfully connected: hanjie
5/5 21:35:33 [8435] - [32minfo[39m:     .                              .o8                     oooo
5/5 21:35:33 [8435] - [32minfo[39m:   .o8                             "888                     `888
5/5 21:35:33 [8435] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 21:35:33 [8435] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 21:35:33 [8435] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 21:35:33 [8435] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 21:35:33 [8435] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 21:35:33 [8435] - [32minfo[39m: ==========================================================================
5/5 21:35:33 [8435] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 21:35:33 [8435] - [32minfo[39m:  
5/5 21:35:33 [8435] - [32minfo[39m: Running in: development
5/5 21:35:33 [8435] - [32minfo[39m: Time: Sat May 05 2018 21:35:33 GMT+0800 (CST)
5/5 21:35:33 [8435] - [32minfo[39m: Connected to MongoDB
5/5 21:35:33 [8435] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 21:35:34 [8435] - [32minfo[39m: SocketServer Running
5/5 21:35:34 [8435] - [34mdebug[39m: Checking Default Settings...
5/5 21:35:34 [8435] - [34mdebug[39m: Starting Runners...
5/5 21:35:34 [8435] - [32minfo[39m: TruDesk Ready
5/5 21:35:34 [8435] - [34mdebug[39m: Number of Tasks: 0
5/5 21:35:34 [8435] - [34mdebug[39m: User successfully connected: hanjie
5/5 21:35:35 [Child:Cache:8437] - [34mdebug[39m: Pulled 0
5/5 21:35:35 [Child:Cache:8437] - [34mdebug[39m: Cache Loaded
5/5 21:38:11 [8435] - [34mdebug[39m: User disconnected: hanjie - aEXliWN1Ed7Xl05CAAAA
5/5 21:38:12 [8435] - [34mdebug[39m: User successfully connected: hanjie
5/5 21:43:00 [8465] - [32minfo[39m:     .                              .o8                     oooo
5/5 21:43:00 [8465] - [32minfo[39m:   .o8                             "888                     `888
5/5 21:43:00 [8465] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 21:43:00 [8465] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 21:43:00 [8465] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 21:43:00 [8465] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 21:43:00 [8465] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 21:43:00 [8465] - [32minfo[39m: ==========================================================================
5/5 21:43:00 [8465] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 21:43:00 [8465] - [32minfo[39m:  
5/5 21:43:00 [8465] - [32minfo[39m: Running in: development
5/5 21:43:00 [8465] - [32minfo[39m: Time: Sat May 05 2018 21:43:00 GMT+0800 (CST)
5/5 21:43:00 [8465] - [32minfo[39m: Connected to MongoDB
5/5 21:43:00 [8465] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 21:43:00 [8465] - [32minfo[39m: SocketServer Running
5/5 21:43:00 [8465] - [34mdebug[39m: Checking Default Settings...
5/5 21:43:00 [8465] - [34mdebug[39m: Starting Runners...
5/5 21:43:00 [8465] - [32minfo[39m: TruDesk Ready
5/5 21:43:00 [8465] - [34mdebug[39m: Number of Tasks: 0
5/5 21:43:01 [8465] - [34mdebug[39m: User successfully connected: hanjie
5/5 21:43:02 [Child:Cache:8467] - [34mdebug[39m: Pulled 0
5/5 21:43:02 [Child:Cache:8467] - [34mdebug[39m: Cache Loaded
5/5 21:45:38 [8485] - [32minfo[39m:     .                              .o8                     oooo
5/5 21:45:38 [8485] - [32minfo[39m:   .o8                             "888                     `888
5/5 21:45:38 [8485] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 21:45:38 [8485] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 21:45:38 [8485] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 21:45:38 [8485] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 21:45:38 [8485] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 21:45:38 [8485] - [32minfo[39m: ==========================================================================
5/5 21:45:38 [8485] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 21:45:38 [8485] - [32minfo[39m:  
5/5 21:45:38 [8485] - [32minfo[39m: Running in: development
5/5 21:45:38 [8485] - [32minfo[39m: Time: Sat May 05 2018 21:45:38 GMT+0800 (CST)
5/5 21:45:38 [8485] - [32minfo[39m: Connected to MongoDB
5/5 21:45:38 [8485] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 21:45:39 [8485] - [32minfo[39m: SocketServer Running
5/5 21:45:39 [8485] - [34mdebug[39m: Checking Default Settings...
5/5 21:45:39 [8485] - [34mdebug[39m: Starting Runners...
5/5 21:45:39 [8485] - [32minfo[39m: TruDesk Ready
5/5 21:45:39 [8485] - [34mdebug[39m: Number of Tasks: 0
5/5 21:45:39 [8485] - [34mdebug[39m: User successfully connected: hanjie
5/5 21:45:40 [Child:Cache:8487] - [34mdebug[39m: Pulled 0
5/5 21:45:40 [Child:Cache:8487] - [34mdebug[39m: Cache Loaded
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
TypeError: Undefined type `Edit` at `editMenu`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:603:11)
    at Schema.path (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:460:29)
    at Schema.add (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:341:12)
    at new Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:89:10)
    at Mongoose.Schema (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/lib/schema.js:61:12)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/group.js:31:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/src/models/ticket.js:23:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
5/5 22:47:06 [8675] - [32minfo[39m:     .                              .o8                     oooo
5/5 22:47:06 [8675] - [32minfo[39m:   .o8                             "888                     `888
5/5 22:47:06 [8675] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 22:47:06 [8675] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 22:47:06 [8675] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 22:47:06 [8675] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 22:47:06 [8675] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 22:47:06 [8675] - [32minfo[39m: ==========================================================================
5/5 22:47:06 [8675] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 22:47:06 [8675] - [32minfo[39m:  
5/5 22:47:06 [8675] - [32minfo[39m: Running in: development
5/5 22:47:06 [8675] - [32minfo[39m: Time: Sat May 05 2018 22:47:06 GMT+0800 (CST)
5/5 22:47:06 [8675] - [32minfo[39m: Connected to MongoDB
5/5 22:47:06 [8675] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 22:47:06 [8675] - [32minfo[39m: SocketServer Running
5/5 22:47:06 [8675] - [34mdebug[39m: Checking Default Settings...
5/5 22:47:06 [8675] - [34mdebug[39m: Starting Runners...
5/5 22:47:06 [8675] - [32minfo[39m: TruDesk Ready
5/5 22:47:06 [8675] - [34mdebug[39m: Number of Tasks: 0
5/5 22:47:08 [Child:Cache:8677] - [34mdebug[39m: Pulled 0
5/5 22:47:08 [Child:Cache:8677] - [34mdebug[39m: Cache Loaded
5/5 22:47:10 [8675] - [34mdebug[39m: User successfully connected: hanjie
Error: [groups.hbs] Missing helper: "../__"
    at model.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at eval (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:54)
    at prog (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval [as main] (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:31)
    at main (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at renderTemplate (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:483:13)
    at render (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:531:5)
    at renderIt (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:593:18)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:613:11
    at parseLayout (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:467:7)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:582:7
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:570:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
Error: [groups.hbs] Missing helper: "../__"
    at model.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at eval (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:54)
    at prog (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval [as main] (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:31)
    at main (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at renderTemplate (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:483:13)
    at render (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:531:5)
    at renderIt (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:593:18)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:613:11
    at parseLayout (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:467:7)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:582:7
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:570:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5/5 23:05:45 [8675] - [34mdebug[39m: User disconnected: hanjie - 80rF0_EaDSA8VCbmAAAA
Error: [groups.hbs] Missing helper: "__"
    at model.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at eval (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:62)
    at prog (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval [as main] (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:31)
    at main (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at renderTemplate (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:483:13)
    at render (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:531:5)
    at renderIt (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:593:18)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:613:11
    at parseLayout (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:467:7)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:582:7
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:570:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5/5 23:15:33 [8784] - [32minfo[39m:     .                              .o8                     oooo
5/5 23:15:33 [8784] - [32minfo[39m:   .o8                             "888                     `888
5/5 23:15:33 [8784] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 23:15:33 [8784] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 23:15:33 [8784] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 23:15:33 [8784] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 23:15:33 [8784] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 23:15:33 [8784] - [32minfo[39m: ==========================================================================
5/5 23:15:33 [8784] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 23:15:33 [8784] - [32minfo[39m:  
5/5 23:15:33 [8784] - [32minfo[39m: Running in: development
5/5 23:15:33 [8784] - [32minfo[39m: Time: Sat May 05 2018 23:15:33 GMT+0800 (CST)
5/5 23:15:33 [8784] - [32minfo[39m: Connected to MongoDB
5/5 23:15:33 [8784] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 23:15:33 [8784] - [32minfo[39m: SocketServer Running
5/5 23:15:33 [8784] - [34mdebug[39m: Checking Default Settings...
5/5 23:15:33 [8784] - [34mdebug[39m: Starting Runners...
5/5 23:15:33 [8784] - [32minfo[39m: TruDesk Ready
5/5 23:15:33 [8784] - [34mdebug[39m: Number of Tasks: 0
5/5 23:15:34 [Child:Cache:8786] - [34mdebug[39m: Pulled 0
5/5 23:15:34 [Child:Cache:8786] - [34mdebug[39m: Cache Loaded
Error: [groups.hbs] Missing helper: "./noop"
    at model.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at eval (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:50)
    at prog (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval [as main] (eval at createFunctionContext (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:31)
    at main (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/Users/hanjie/Application/web/IntellAgent/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at renderTemplate (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:483:13)
    at render (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:531:5)
    at renderIt (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:593:18)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:613:11
    at parseLayout (/Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:467:7)
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:582:7
    at /Users/hanjie/Application/web/IntellAgent/node_modules/express-hbs/lib/hbs.js:570:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5/5 23:15:56 [8784] - [34mdebug[39m: User successfully connected: hanjie
5/5 23:17:41 [8804] - [32minfo[39m:     .                              .o8                     oooo
5/5 23:17:41 [8804] - [32minfo[39m:   .o8                             "888                     `888
5/5 23:17:41 [8804] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 23:17:41 [8804] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 23:17:41 [8804] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 23:17:41 [8804] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 23:17:41 [8804] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 23:17:41 [8804] - [32minfo[39m: ==========================================================================
5/5 23:17:41 [8804] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 23:17:41 [8804] - [32minfo[39m:  
5/5 23:17:41 [8804] - [32minfo[39m: Running in: development
5/5 23:17:41 [8804] - [32minfo[39m: Time: Sat May 05 2018 23:17:41 GMT+0800 (CST)
5/5 23:17:41 [8804] - [32minfo[39m: Connected to MongoDB
5/5 23:17:41 [8804] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 23:17:41 [8804] - [32minfo[39m: SocketServer Running
5/5 23:17:41 [8804] - [34mdebug[39m: Checking Default Settings...
5/5 23:17:42 [8804] - [34mdebug[39m: Starting Runners...
5/5 23:17:42 [8804] - [32minfo[39m: TruDesk Ready
5/5 23:17:42 [8804] - [34mdebug[39m: Number of Tasks: 0
5/5 23:17:43 [Child:Cache:8806] - [34mdebug[39m: Pulled 0
5/5 23:17:43 [Child:Cache:8806] - [34mdebug[39m: Cache Loaded
5/5 23:17:45 [8804] - [34mdebug[39m: User successfully connected: hanjie
5/5 23:22:33 [8832] - [32minfo[39m:     .                              .o8                     oooo
5/5 23:22:33 [8832] - [32minfo[39m:   .o8                             "888                     `888
5/5 23:22:33 [8832] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 23:22:33 [8832] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 23:22:33 [8832] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 23:22:33 [8832] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 23:22:33 [8832] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 23:22:33 [8832] - [32minfo[39m: ==========================================================================
5/5 23:22:33 [8832] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 23:22:33 [8832] - [32minfo[39m:  
5/5 23:22:33 [8832] - [32minfo[39m: Running in: development
5/5 23:22:33 [8832] - [32minfo[39m: Time: Sat May 05 2018 23:22:33 GMT+0800 (CST)
5/5 23:22:34 [8832] - [32minfo[39m: Connected to MongoDB
5/5 23:22:34 [8832] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 23:22:34 [8832] - [32minfo[39m: SocketServer Running
5/5 23:22:34 [8832] - [34mdebug[39m: Checking Default Settings...
5/5 23:22:34 [8832] - [34mdebug[39m: Starting Runners...
5/5 23:22:34 [8832] - [32minfo[39m: TruDesk Ready
5/5 23:22:34 [8832] - [34mdebug[39m: Number of Tasks: 0
5/5 23:22:35 [Child:Cache:8834] - [34mdebug[39m: Pulled 0
5/5 23:22:35 [Child:Cache:8834] - [34mdebug[39m: Cache Loaded
5/5 23:22:36 [8832] - [34mdebug[39m: User successfully connected: hanjie
5/5 23:25:15 [8845] - [32minfo[39m:     .                              .o8                     oooo
5/5 23:25:15 [8845] - [32minfo[39m:   .o8                             "888                     `888
5/5 23:25:15 [8845] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/5 23:25:15 [8845] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/5 23:25:15 [8845] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/5 23:25:15 [8845] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/5 23:25:15 [8845] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/5 23:25:15 [8845] - [32minfo[39m: ==========================================================================
5/5 23:25:15 [8845] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/5 23:25:15 [8845] - [32minfo[39m:  
5/5 23:25:15 [8845] - [32minfo[39m: Running in: development
5/5 23:25:15 [8845] - [32minfo[39m: Time: Sat May 05 2018 23:25:15 GMT+0800 (CST)
5/5 23:25:15 [8845] - [32minfo[39m: Connected to MongoDB
5/5 23:25:15 [8845] - [32minfo[39m: TruDesk is now listening on port: 8118
5/5 23:25:15 [8845] - [32minfo[39m: SocketServer Running
5/5 23:25:15 [8845] - [34mdebug[39m: Checking Default Settings...
5/5 23:25:15 [8845] - [34mdebug[39m: Starting Runners...
5/5 23:25:15 [8845] - [32minfo[39m: TruDesk Ready
5/5 23:25:15 [8845] - [34mdebug[39m: Number of Tasks: 0
5/5 23:25:16 [Child:Cache:8847] - [34mdebug[39m: Pulled 0
5/5 23:25:16 [Child:Cache:8847] - [34mdebug[39m: Cache Loaded
5/5 23:25:17 [8845] - [34mdebug[39m: User successfully connected: hanjie
5/6 01:33:18 [Child:Cache:8847] - [34mdebug[39m: Refreshing Cache...
5/6 01:33:18 [Child:Cache:8847] - [34mdebug[39m: Pulled 0
5/6 05:02:25 [Child:Cache:8847] - [34mdebug[39m: Refreshing Cache...
5/6 05:02:25 [Child:Cache:8847] - [34mdebug[39m: Pulled 0
5/6 08:18:18 [1069] - [32minfo[39m:     .                              .o8                     oooo
5/6 08:18:18 [1069] - [32minfo[39m:   .o8                             "888                     `888
5/6 08:18:18 [1069] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/6 08:18:18 [1069] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/6 08:18:18 [1069] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/6 08:18:18 [1069] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/6 08:18:18 [1069] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/6 08:18:18 [1069] - [32minfo[39m: ==========================================================================
5/6 08:18:18 [1069] - [32minfo[39m: TruDesk v1.0.0 Copyright (C) 2014-2018 Chris Brame
5/6 08:18:18 [1069] - [32minfo[39m:  
5/6 08:18:18 [1069] - [32minfo[39m: Running in: development
5/6 08:18:18 [1069] - [32minfo[39m: Time: Sun May 06 2018 08:18:18 GMT+0800 (CST)
5/6 08:18:18 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:18 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:18 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
5/6 08:18:28 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
5/6 08:18:28 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:28 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:28 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
5/6 08:18:38 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
5/6 08:18:38 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:38 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:38 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
5/6 08:18:48 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
5/6 08:18:48 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:48 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:48 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
5/6 08:18:58 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
5/6 08:18:58 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:58 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:18:58 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
5/6 08:19:08 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:08 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
5/6 08:19:08 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:08 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
5/6 08:19:18 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
5/6 08:19:18 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:18 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:18 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
5/6 08:19:28 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
5/6 08:19:28 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:28 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:28 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
5/6 08:19:38 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
5/6 08:19:38 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:38 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:38 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
5/6 08:19:48 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
5/6 08:19:48 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:48 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:48 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
5/6 08:19:58 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
5/6 08:19:58 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:58 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:19:58 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
5/6 08:20:08 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
5/6 08:20:08 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:08 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:08 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
5/6 08:20:18 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:18 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
5/6 08:20:18 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:18 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
5/6 08:20:28 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
5/6 08:20:28 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:28 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:28 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
5/6 08:20:38 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
5/6 08:20:38 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:38 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:38 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
5/6 08:20:48 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
5/6 08:20:49 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:49 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:20:49 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
5/6 08:25:20 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
5/6 08:25:20 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:25:20 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:25:20 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
5/6 08:25:31 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
5/6 08:25:31 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:25:31 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:25:31 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
5/6 08:25:41 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
5/6 08:25:41 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
5/6 08:25:41 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:25:41 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
5/6 08:25:51 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
5/6 08:25:51 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:25:51 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:25:51 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
5/6 08:26:01 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:26:01 [1069] - [33mwarn[39m: Retrying to connect to MongoDB in 10secs...
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
5/6 08:26:01 [1069] - [31merror[39m: Oh no, something went wrong with DB! - failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
5/6 08:26:01 [1069] - [31merror[39m: FETAL: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:1069) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at Pool.emit (events.js:180:13)
    at Pool.emit (domain.js:421:20)
    at Connection.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Connection.emit (domain.js:421:20)
    at Socket.<anonymous> (/Users/hanjie/Application/web/IntellAgent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
(node:1069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
5/6 08:26:11 [1069] - [32minfo[39m: Connected to MongoDB
5/6 08:26:11 [1069] - [32minfo[39m: TruDesk is now listening on port: 8118
5/6 08:26:11 [1069] - [32minfo[39m: SocketServer Running
5/6 08:26:11 [1069] - [34mdebug[39m: Checking Default Settings...
5/6 08:26:11 [1069] - [34mdebug[39m: Starting Runners...
5/6 08:26:11 [1069] - [32minfo[39m: TruDesk Ready
5/6 08:26:11 [1069] - [34mdebug[39m: Number of Tasks: 0
5/6 08:26:13 [Child:Cache:1110] - [34mdebug[39m: Pulled 0
5/6 08:26:13 [Child:Cache:1110] - [34mdebug[39m: Cache Loaded
